on: [push]

jobs:
  build:
    environment: sandbox
    env:
      TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - run: env
      - run: echo $TWINE_PASSWORD