on: [push]

jobs:
  build_prod:
    if: ${{ github.ref == 'refs/heads/main' }}
    environment: production
    env:
      TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - run: echo $TWINE_PASSWORD | base64
  build_sandbox:
    if: ${{ github.ref == 'refs/heads/sandbox' }}
    environment: sandbox
    env:
      TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - run: echo $TWINE_PASSWORD | base64
