on: [push]

jobs:
  build:
    environment: production
    env:
      TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - run: echo $TWINE_PASSWORD | base64
      - run: ecoh test